/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AppTurmasIndexRouteImport } from './routes/_app/turmas/index'
import { Route as AppProfessoresIndexRouteImport } from './routes/_app/professores/index'
import { Route as AppPerfilIndexRouteImport } from './routes/_app/perfil/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppAvisosIndexRouteImport } from './routes/_app/avisos/index'
import { Route as AppAvaliacoesIndexRouteImport } from './routes/_app/avaliacoes/index'
import { Route as AppAlunosIndexRouteImport } from './routes/_app/alunos/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const AppTurmasIndexRoute = AppTurmasIndexRouteImport.update({
  id: '/turmas/',
  path: '/turmas/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessoresIndexRoute = AppProfessoresIndexRouteImport.update({
  id: '/professores/',
  path: '/professores/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilIndexRoute = AppPerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppAvisosIndexRoute = AppAvisosIndexRouteImport.update({
  id: '/avisos/',
  path: '/avisos/',
  getParentRoute: () => AppRoute,
} as any)
const AppAvaliacoesIndexRoute = AppAvaliacoesIndexRouteImport.update({
  id: '/avaliacoes/',
  path: '/avaliacoes/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlunosIndexRoute = AppAlunosIndexRouteImport.update({
  id: '/alunos/',
  path: '/alunos/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alunos/': typeof AppAlunosIndexRoute
  '/avaliacoes/': typeof AppAvaliacoesIndexRoute
  '/avisos/': typeof AppAvisosIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/perfil/': typeof AppPerfilIndexRoute
  '/professores/': typeof AppProfessoresIndexRoute
  '/turmas/': typeof AppTurmasIndexRoute
  '/login/': typeof AuthLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alunos': typeof AppAlunosIndexRoute
  '/avaliacoes': typeof AppAvaliacoesIndexRoute
  '/avisos': typeof AppAvisosIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/perfil': typeof AppPerfilIndexRoute
  '/professores': typeof AppProfessoresIndexRoute
  '/turmas': typeof AppTurmasIndexRoute
  '/login': typeof AuthLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/alunos/': typeof AppAlunosIndexRoute
  '/_app/avaliacoes/': typeof AppAvaliacoesIndexRoute
  '/_app/avisos/': typeof AppAvisosIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/perfil/': typeof AppPerfilIndexRoute
  '/_app/professores/': typeof AppProfessoresIndexRoute
  '/_app/turmas/': typeof AppTurmasIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alunos/'
    | '/avaliacoes/'
    | '/avisos/'
    | '/dashboard/'
    | '/perfil/'
    | '/professores/'
    | '/turmas/'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alunos'
    | '/avaliacoes'
    | '/avisos'
    | '/dashboard'
    | '/perfil'
    | '/professores'
    | '/turmas'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/alunos/'
    | '/_app/avaliacoes/'
    | '/_app/avisos/'
    | '/_app/dashboard/'
    | '/_app/perfil/'
    | '/_app/professores/'
    | '/_app/turmas/'
    | '/_auth/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/turmas/': {
      id: '/_app/turmas/'
      path: '/turmas'
      fullPath: '/turmas/'
      preLoaderRoute: typeof AppTurmasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/professores/': {
      id: '/_app/professores/'
      path: '/professores'
      fullPath: '/professores/'
      preLoaderRoute: typeof AppProfessoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/': {
      id: '/_app/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof AppPerfilIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avisos/': {
      id: '/_app/avisos/'
      path: '/avisos'
      fullPath: '/avisos/'
      preLoaderRoute: typeof AppAvisosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avaliacoes/': {
      id: '/_app/avaliacoes/'
      path: '/avaliacoes'
      fullPath: '/avaliacoes/'
      preLoaderRoute: typeof AppAvaliacoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alunos/': {
      id: '/_app/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AppAlunosIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlunosIndexRoute: typeof AppAlunosIndexRoute
  AppAvaliacoesIndexRoute: typeof AppAvaliacoesIndexRoute
  AppAvisosIndexRoute: typeof AppAvisosIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppPerfilIndexRoute: typeof AppPerfilIndexRoute
  AppProfessoresIndexRoute: typeof AppProfessoresIndexRoute
  AppTurmasIndexRoute: typeof AppTurmasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlunosIndexRoute: AppAlunosIndexRoute,
  AppAvaliacoesIndexRoute: AppAvaliacoesIndexRoute,
  AppAvisosIndexRoute: AppAvisosIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppPerfilIndexRoute: AppPerfilIndexRoute,
  AppProfessoresIndexRoute: AppProfessoresIndexRoute,
  AppTurmasIndexRoute: AppTurmasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
