/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherTurmasIndexRouteImport } from './routes/teacher/turmas/index'
import { Route as TeacherPerfilIndexRouteImport } from './routes/teacher/perfil/index'
import { Route as TeacherDashboardIndexRouteImport } from './routes/teacher/dashboard/index'
import { Route as TeacherAvisosIndexRouteImport } from './routes/teacher/avisos/index'
import { Route as TeacherAvaliacoesIndexRouteImport } from './routes/teacher/avaliacoes/index'
import { Route as AdminUsuariosIndexRouteImport } from './routes/admin/usuarios/index'
import { Route as AdminTurmasIndexRouteImport } from './routes/admin/turmas/index'
import { Route as AdminProfessoresIndexRouteImport } from './routes/admin/professores/index'
import { Route as AdminPerfilIndexRouteImport } from './routes/admin/perfil/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminAvisosIndexRouteImport } from './routes/admin/avisos/index'
import { Route as AdminAvaliacoesIndexRouteImport } from './routes/admin/avaliacoes/index'
import { Route as AdminAlunosIndexRouteImport } from './routes/admin/alunos/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTurmasIndexRoute = TeacherTurmasIndexRouteImport.update({
  id: '/turmas/',
  path: '/turmas/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherPerfilIndexRoute = TeacherPerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDashboardIndexRoute = TeacherDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAvisosIndexRoute = TeacherAvisosIndexRouteImport.update({
  id: '/avisos/',
  path: '/avisos/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAvaliacoesIndexRoute = TeacherAvaliacoesIndexRouteImport.update({
  id: '/avaliacoes/',
  path: '/avaliacoes/',
  getParentRoute: () => TeacherRoute,
} as any)
const AdminUsuariosIndexRoute = AdminUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTurmasIndexRoute = AdminTurmasIndexRouteImport.update({
  id: '/turmas/',
  path: '/turmas/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfessoresIndexRoute = AdminProfessoresIndexRouteImport.update({
  id: '/professores/',
  path: '/professores/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfilIndexRoute = AdminPerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvisosIndexRoute = AdminAvisosIndexRouteImport.update({
  id: '/avisos/',
  path: '/avisos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvaliacoesIndexRoute = AdminAvaliacoesIndexRouteImport.update({
  id: '/avaliacoes/',
  path: '/avaliacoes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosIndexRoute = AdminAlunosIndexRouteImport.update({
  id: '/alunos/',
  path: '/alunos/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/login/': typeof AuthLoginIndexRoute
  '/admin/alunos/': typeof AdminAlunosIndexRoute
  '/admin/avaliacoes/': typeof AdminAvaliacoesIndexRoute
  '/admin/avisos/': typeof AdminAvisosIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/perfil/': typeof AdminPerfilIndexRoute
  '/admin/professores/': typeof AdminProfessoresIndexRoute
  '/admin/turmas/': typeof AdminTurmasIndexRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
  '/teacher/avaliacoes/': typeof TeacherAvaliacoesIndexRoute
  '/teacher/avisos/': typeof TeacherAvisosIndexRoute
  '/teacher/dashboard/': typeof TeacherDashboardIndexRoute
  '/teacher/perfil/': typeof TeacherPerfilIndexRoute
  '/teacher/turmas/': typeof TeacherTurmasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/login': typeof AuthLoginIndexRoute
  '/admin/alunos': typeof AdminAlunosIndexRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesIndexRoute
  '/admin/avisos': typeof AdminAvisosIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/perfil': typeof AdminPerfilIndexRoute
  '/admin/professores': typeof AdminProfessoresIndexRoute
  '/admin/turmas': typeof AdminTurmasIndexRoute
  '/admin/usuarios': typeof AdminUsuariosIndexRoute
  '/teacher/avaliacoes': typeof TeacherAvaliacoesIndexRoute
  '/teacher/avisos': typeof TeacherAvisosIndexRoute
  '/teacher/dashboard': typeof TeacherDashboardIndexRoute
  '/teacher/perfil': typeof TeacherPerfilIndexRoute
  '/teacher/turmas': typeof TeacherTurmasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/admin/alunos/': typeof AdminAlunosIndexRoute
  '/admin/avaliacoes/': typeof AdminAvaliacoesIndexRoute
  '/admin/avisos/': typeof AdminAvisosIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/perfil/': typeof AdminPerfilIndexRoute
  '/admin/professores/': typeof AdminProfessoresIndexRoute
  '/admin/turmas/': typeof AdminTurmasIndexRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
  '/teacher/avaliacoes/': typeof TeacherAvaliacoesIndexRoute
  '/teacher/avisos/': typeof TeacherAvisosIndexRoute
  '/teacher/dashboard/': typeof TeacherDashboardIndexRoute
  '/teacher/perfil/': typeof TeacherPerfilIndexRoute
  '/teacher/turmas/': typeof TeacherTurmasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/teacher'
    | '/login/'
    | '/admin/alunos/'
    | '/admin/avaliacoes/'
    | '/admin/avisos/'
    | '/admin/dashboard/'
    | '/admin/perfil/'
    | '/admin/professores/'
    | '/admin/turmas/'
    | '/admin/usuarios/'
    | '/teacher/avaliacoes/'
    | '/teacher/avisos/'
    | '/teacher/dashboard/'
    | '/teacher/perfil/'
    | '/teacher/turmas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/teacher'
    | '/login'
    | '/admin/alunos'
    | '/admin/avaliacoes'
    | '/admin/avisos'
    | '/admin/dashboard'
    | '/admin/perfil'
    | '/admin/professores'
    | '/admin/turmas'
    | '/admin/usuarios'
    | '/teacher/avaliacoes'
    | '/teacher/avisos'
    | '/teacher/dashboard'
    | '/teacher/perfil'
    | '/teacher/turmas'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/admin'
    | '/teacher'
    | '/_auth/login/'
    | '/admin/alunos/'
    | '/admin/avaliacoes/'
    | '/admin/avisos/'
    | '/admin/dashboard/'
    | '/admin/perfil/'
    | '/admin/professores/'
    | '/admin/turmas/'
    | '/admin/usuarios/'
    | '/teacher/avaliacoes/'
    | '/teacher/avisos/'
    | '/teacher/dashboard/'
    | '/teacher/perfil/'
    | '/teacher/turmas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/turmas/': {
      id: '/teacher/turmas/'
      path: '/turmas'
      fullPath: '/teacher/turmas/'
      preLoaderRoute: typeof TeacherTurmasIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/perfil/': {
      id: '/teacher/perfil/'
      path: '/perfil'
      fullPath: '/teacher/perfil/'
      preLoaderRoute: typeof TeacherPerfilIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/dashboard/': {
      id: '/teacher/dashboard/'
      path: '/dashboard'
      fullPath: '/teacher/dashboard/'
      preLoaderRoute: typeof TeacherDashboardIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/avisos/': {
      id: '/teacher/avisos/'
      path: '/avisos'
      fullPath: '/teacher/avisos/'
      preLoaderRoute: typeof TeacherAvisosIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/avaliacoes/': {
      id: '/teacher/avaliacoes/'
      path: '/avaliacoes'
      fullPath: '/teacher/avaliacoes/'
      preLoaderRoute: typeof TeacherAvaliacoesIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/admin/usuarios/': {
      id: '/admin/usuarios/'
      path: '/usuarios'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AdminUsuariosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/turmas/': {
      id: '/admin/turmas/'
      path: '/turmas'
      fullPath: '/admin/turmas/'
      preLoaderRoute: typeof AdminTurmasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/professores/': {
      id: '/admin/professores/'
      path: '/professores'
      fullPath: '/admin/professores/'
      preLoaderRoute: typeof AdminProfessoresIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfil/': {
      id: '/admin/perfil/'
      path: '/perfil'
      fullPath: '/admin/perfil/'
      preLoaderRoute: typeof AdminPerfilIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avisos/': {
      id: '/admin/avisos/'
      path: '/avisos'
      fullPath: '/admin/avisos/'
      preLoaderRoute: typeof AdminAvisosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avaliacoes/': {
      id: '/admin/avaliacoes/'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes/'
      preLoaderRoute: typeof AdminAvaliacoesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos/': {
      id: '/admin/alunos/'
      path: '/alunos'
      fullPath: '/admin/alunos/'
      preLoaderRoute: typeof AdminAlunosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AdminRouteChildren {
  AdminAlunosIndexRoute: typeof AdminAlunosIndexRoute
  AdminAvaliacoesIndexRoute: typeof AdminAvaliacoesIndexRoute
  AdminAvisosIndexRoute: typeof AdminAvisosIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminPerfilIndexRoute: typeof AdminPerfilIndexRoute
  AdminProfessoresIndexRoute: typeof AdminProfessoresIndexRoute
  AdminTurmasIndexRoute: typeof AdminTurmasIndexRoute
  AdminUsuariosIndexRoute: typeof AdminUsuariosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlunosIndexRoute: AdminAlunosIndexRoute,
  AdminAvaliacoesIndexRoute: AdminAvaliacoesIndexRoute,
  AdminAvisosIndexRoute: AdminAvisosIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminPerfilIndexRoute: AdminPerfilIndexRoute,
  AdminProfessoresIndexRoute: AdminProfessoresIndexRoute,
  AdminTurmasIndexRoute: AdminTurmasIndexRoute,
  AdminUsuariosIndexRoute: AdminUsuariosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TeacherRouteChildren {
  TeacherAvaliacoesIndexRoute: typeof TeacherAvaliacoesIndexRoute
  TeacherAvisosIndexRoute: typeof TeacherAvisosIndexRoute
  TeacherDashboardIndexRoute: typeof TeacherDashboardIndexRoute
  TeacherPerfilIndexRoute: typeof TeacherPerfilIndexRoute
  TeacherTurmasIndexRoute: typeof TeacherTurmasIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAvaliacoesIndexRoute: TeacherAvaliacoesIndexRoute,
  TeacherAvisosIndexRoute: TeacherAvisosIndexRoute,
  TeacherDashboardIndexRoute: TeacherDashboardIndexRoute,
  TeacherPerfilIndexRoute: TeacherPerfilIndexRoute,
  TeacherTurmasIndexRoute: TeacherTurmasIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
